### ISSUE TITLE
How to make tests?

### ISSUE THREAD

**Issue by marcfedorow** [MjVlad/Labs#10]
#5 #6 #7 #8 #9
Probably, it is a good idea to create `bool operator=(stack&, std::stack);`.
While you have the reference class it could be used to check if your class works.
To avoid your and std stack inconsistencies, you may create your std-based stack [inherited](http://www.cplusplus.com/doc/tutorial/inheritance/) on STL one.

This is advice. Still, you can re-write tests with your own logic (e.g. iterators or something).

**Comment by ghost** [comment]
u can see an example [here](https://github.com/pooo-m/lab/blob/master/UnitTest1/UnitTest1.cpp)
